default_language_version:
  python: python3.12
files: "^(tests|src|notebooks)/.*$"
exclude: "\\.svg$"
default_stages: [pre-commit, post-commit, pre-push]
repos:
  # Apply black formatting
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args:
          - "--config"
          - "./pyproject.toml"

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--settings-file"
          - "./pyproject.toml"

  # Strip notebook output and metadata
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - "--drop-empty-cells"
